services:
  db:
    hostname: db
    image: postgis/postgis:17-3.5-alpine
    shm_size: 512m
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - lan_access
    ports:
      - "${DB_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    hostname: iqs
    image: iqs-1.0.0
    tty: true
    build:
      context: .
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app/django-iqs
    command: [
        "python3",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    networks:
      - lan_access
    ports:
      - 8000:8000
    volumes:
      - .:/app # dev mode !!!
      - "${DATA_DIR}:/data"

networks:
  lan_access:
    driver: bridge

volumes:
  pgdata: {}
